spring.application.name=JobShield1

spring.datasource.url=jdbc:mysql://bqrssl4frsc6blog9yyw-mysql.services.clever-cloud.com:3306/bqrssl4frsc6blog9yyw?useSSL=false&serverTimezone=UTC

spring.datasource.username=u51s9b57mlz75vvr

spring.datasource.password=02T0RmwzifdrYORtfwAT

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
server.port=8081
